[config]

# For additional information, please see the METplus Users Guide.
# https://metplus.readthedocs.io/en/latest/Users_Guide

###
# Processes to run
# https://metplus.readthedocs.io/en/latest/Users_Guide/systemconfiguration.html#process-list
###

PROCESS_LIST = PointStat


###
# Time Info
# LOOP_BY options are INIT, VALID, RETRO, and REALTIME
# If set to INIT or RETRO:
#   INIT_TIME_FMT, INIT_BEG, INIT_END, and INIT_INCREMENT must also be set
# If set to VALID or REALTIME:
#   VALID_TIME_FMT, VALID_BEG, VALID_END, and VALID_INCREMENT must also be set
# LEAD_SEQ is the list of forecast leads to process
# https://metplus.readthedocs.io/en/latest/Users_Guide/systemconfiguration.html#timing-control
###

LOOP_BY = INIT
INIT_TIME_FMT = %Y%m%d%H
INIT_BEG = 2025040606
INIT_END = 2025040606
INIT_INCREMENT = 1M

LEAD_SEQ = 30


###
# File I/O
# https://metplus.readthedocs.io/en/latest/Users_Guide/systemconfiguration.html#directory-and-filename-template-info
###

CONFIG_DIR = /config
CONFIG_DIR = /Users/mccabe/i-wrf/use_cases/Renewable_Energy/METplus
INPUT_BASE = /data/input
INPUT_BASE = /Users/mccabe/data/iwrf/renewable_energy

FCST_POINT_STAT_INPUT_DIR = {INPUT_BASE}/wrf
#FCST_POINT_STAT_INPUT_TEMPLATE = {init?fmt=%Y%m%d_%H}/wrfout/wrfout_d01_{valid?fmt=%Y-%m-%d_%H:%M:%S}
FCST_POINT_STAT_INPUT_TEMPLATE = {init?fmt=%Y%m%d_%H}/wrfout/wrfout_zlev_d01_{valid?fmt=%Y-%m-%d_%H:%M:%S}

OBS_POINT_STAT_INPUT_DIR =
OBS_POINT_STAT_INPUT_TEMPLATE = PYTHON_NUMPY= {CONFIG_DIR}/read_nysm_obs.py --debug {INPUT_BASE}/obs/profiler/{valid?fmt=%Y%m%d}.nc velocity --station_file {INPUT_BASE}/obs/profiler.csv

POINT_STAT_OUTPUT_DIR = {OUTPUT_BASE}/point_stat


###
# Field Info
# https://metplus.readthedocs.io/en/latest/Users_Guide/systemconfiguration.html#field-info
###


FCST_VAR1_NAME = S_ZL
FCST_VAR1_LEVELS = "(0,@-100,*,*)"
OBS_VAR1_NAME = velocity
OBS_VAR1_LEVELS = Z100



###
# PointStat Settings
# https://metplus.readthedocs.io/en/latest/Users_Guide/wrappers.html#pointstat
###

#POINT_STAT_OUTPUT_FLAG_FHO =
#POINT_STAT_OUTPUT_FLAG_CTC =
#POINT_STAT_OUTPUT_FLAG_CTS =
#POINT_STAT_OUTPUT_FLAG_MCTC =
#POINT_STAT_OUTPUT_FLAG_MCTS =
POINT_STAT_OUTPUT_FLAG_CNT = STAT
#POINT_STAT_OUTPUT_FLAG_SL1L2 = STAT
#POINT_STAT_OUTPUT_FLAG_SAL1L2 =
#POINT_STAT_OUTPUT_FLAG_VL1L2 = STAT
#POINT_STAT_OUTPUT_FLAG_VAL1L2 =
#POINT_STAT_OUTPUT_FLAG_VCNT =
#POINT_STAT_OUTPUT_FLAG_PCT =
#POINT_STAT_OUTPUT_FLAG_PSTD =
#POINT_STAT_OUTPUT_FLAG_PJC =
#POINT_STAT_OUTPUT_FLAG_PRC =
#POINT_STAT_OUTPUT_FLAG_ECNT =
#POINT_STAT_OUTPUT_FLAG_RPS =
#POINT_STAT_OUTPUT_FLAG_ECLV =
#POINT_STAT_OUTPUT_FLAG_MPR =
#POINT_STAT_OUTPUT_FLAG_ORANK =

OBS_POINT_STAT_WINDOW_BEGIN = -900
OBS_POINT_STAT_WINDOW_END = 900

POINT_STAT_OFFSETS = 0

MODEL = WRF

POINT_STAT_DESC = NA
OBTYPE =

POINT_STAT_OUTPUT_PREFIX =

POINT_STAT_MESSAGE_TYPE = ADPUPA, ADPSFC
