sim_hrs: 48
template_dir: /glade/work/jaredlee/nsf_i-wrf/use_cases/renewable_energy/templates
wps_ins_dir: /glade/u/home/jaredlee/programs/WPS-4.6-dmpar-casper
wrf_ins_dir: /glade/u/home/jaredlee/programs/WRF-4.6
wps_run_dir: /glade/derecho/scratch/jaredlee/nsf_i-wrf/renewable_energy/wps
wrf_run_dir: /glade/derecho/scratch/jaredlee/nsf_i-wrf/renewable_energy/wrf
grib_dir: /glade/derecho/scratch/jaredlee/data/hrrr
icbc_model: HRRR
icbc_source: AWS
icbc_fc_dt: 0
icbc_analysis: False
hrrr_native: False
get_icbc: True
do_geogrid: True
do_ungrib: True
do_avg_tsfc: True
use_tavgsfc: True
do_metgrid: True
do_real: True
do_wrf: True
archive: False
account: NWSA0002
