name: Documentation
on:
  push:
    branches:
      - develop
      - feature**
      - main**
      - bugfix**
    paths:
      - docs/**
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch:

jobs:
  documentation:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade -r docs/requirements.txt
      - name: Build Documentation
        run: ./.github/jobs/build_documentation.sh
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: i-wrf_documentation
          path: artifact/documentation
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: documentation_warnings.log
          path: artifact/doc_warnings.log
          if-no-files-found: ignore
